Repository euslisp/jskeus, pull requests merged in 2018-07, with the labels that each got.

#429 fix load time.l in current directory
  irteus/irtext.l
Labels: enhancement

#430 CMakeList.txt: enable to run compile when .o is removed
  irteus/Makefile
Labels: enhancement

#483 [irteus/test/matrix.l] add test case of rotating around x-axis
  irteus/test/matrix.l
Labels: wait_for_newer_euslsip

#469 Set minjerk end position to last given value
  irteus/irtutil.l
Labels: PR/WaitForMoreFeedback

#486 [irteus/irtgeo.l] move :move-coords method to coordinates class
  irteus/irtgeo.l
Labels: PR/MergeOK

#485 [irteus/test/geo.l] add test-vector-angle.
  irteus/test/geo.l
Labels: PR/MergeOK, wait_for_newer_euslsip

#461 Fix invalid indexing in collision link pair calculation
  irteus/irtmodel.l
  irteus/test/test-irt-motion.l
Labels: PR/MergeOK
