Repository euslisp/jskeus, pull requests merged in 2020-06, with the labels that each got.

#558 warn misisng color names
  irteus/irtgl.l
Labels: PR/MergeOK

#554 [irteus/irtmath.l] Add inverse matrix of complex matrix and eigen decompose considering complex number
  irteus/irtmath.l
  irteus/test/mathtest.l
Labels: PR/NeedFix

#248 add irtstl.l, irtwrl.l : copied from wrl2eus.l and read-stl.l
  irteus/Makefile
  irteus/compile_irtg.l
  irteus/irtext.l
  irteus/irtstl.l
  irteus/irtwrl.l
  irteus/test/test-cad.l
Labels: PR/WaitForMoreFeedback, newfeature

#536 inverse-kinematics: check length of thre and rthre is equal to move-target
  irteus/irtmodel.l
Labels: PR/MergeOK
